apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: "timebeat-share-key"
  creationTimestamp: null
  labels:
    app: elasticsearch
  name: elasticsearch
spec:
  type: LoadBalancer
  ports:
  - name: "elastic-noncluster"
    port: 9200
    targetPort: 9200
    protocol: TCP
  selector:
    app: elasticsearch
