apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: "timebeat-share-key"
  creationTimestamp: null
  labels:
    app: grafana
  name: grafana
spec:
  type: LoadBalancer
  ports:
  - name: "3000"
    port: 80
    targetPort: 3000
  selector:
    app: grafana
status:
  loadBalancer: {}
